import {Noto_Sans} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { ToastContainer } from "react-toastify";

const noto = Noto_Sans({
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${noto.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
       <Navbar/>
        {children}
        <ToastContainer/>
        <Footer/>
        </body>
    </html>
  );
}
